#echo "==============================================================================================================="
#echo "= if you are not moving, you are staying on the same place… If you are not searching, youll never find…        "
#echo "==============================================================================================================="
#echo "= i tried to be normal once... i didn't like it                                                               ="
#echo "# Muž se nepozná podle perfektní košile, ale podle toho, že je schopen překonávat nepříjemné a obtížné překážky, dokáže „zatnout zuby“ a zvládat i to, co jej k smrti nebaví."
#echo "==============================================================================================================="
#echo "= if you can dream it you can do it                                                                           ="
#echo "==============================================================================================================="
#echo "= Better to be lost to one's passion, than to lose one's passion                                              ="
#echo "= Zivot je zavod s casem, ktery bohuzel nikdy nemuzeme vyhrat                                                 ="
#echo "= Pekar kralem: brouzdat se po loukach a poslouchat hvizdat drozdy                                            ="
#echo "= Whatever you dream you can do, begin it. Boldness has genius, power and magic in it. Begin it now. - Goethe ="
#echo "= Success comes from persistently improving and inventing, not from persistently promoting what's not working.="
#echo "= The only source of knowledge is experience ~ Albert Einstein                                                ="
#echo "==============================================================================================================="
#echo "= Joel: \"Decisions in 10minutes or less, or the next one is free\"                                           ="
#echo "==============================================================================================================="
#echo "= Cicero: \"Dum spiro spero\" (While I breathe, I hope)"
#echo "==============================================================================================================="
#echo "stahnout: http://www.myspace.com/theafghanwhigs "
#echo "poslechnout:  Mad Season - Above (1995)"
#echo "Candy dulfer - nejslavnejsi saxofontiska"
#echo "cist: michael chabon - zidovský policejní klub"
#echo "------------------------------------------------------------"
#echo "Kite: http://koudik.rajce.idnes.cz/"
#echo "Hezke fotky: http://pani-malina.rajce.idnes.cz/portrety/"
#echo "dat na osobni stranky linky na dobre zapoctaky, ktere vznikly v ramci OOP"
#echo "Middleware'08 presentation: \"do you work, don't be stupid\""
#echo "------------------------------------------------------------"
#echo "Cim dele jsem tu a uvedomuji si, co je vlastne zivot, tím vic chapu, ze nezalezi na tom, jak a kdy clovek zemre, ale jestli nekdy skutecne a opravdove zil"
#echo "Dustojník cestne legie Miksche si klade za cest Vám oznámit, ze byl povolán na vecnost. Bez kvetin a slz."
#echo "http://www.youtube.com/watch?v=pnVAE91E7kM"
#echo "When brilliant people create things, study them."
#
#echo -e "\/--------------------------------------\/
#This is our decision to live fast and die young.
#We've got the vision, now let's have some fun.
#Yeah it's overwhelming, but what else can we do?
#Get jobs in offices and wake up for the morning commute? (MGMT)
#echo     "Svědomí národa je jako veliká kniha popsaná činy těch, kteří v nejdůležitějších dobách historie národa neváhali předstoupit před nepřítele a položit oběti," řekl #veterán před deseti lety při návštěvě Česka. "O svobodu se neprosí, o svobodu se bojuje,"
#\/--------------------------------------\/"
#echo "\/----------------------------------------------------------------\/"
#echo "->  work smart, then work really hard, do not forget to have fun"
#echo "--> I tried to be normal once... I didn't like it. <--"
#echo "/\----------------------------------------------------------------/\\"
#ZBYVA=$(expr `date --date '2012-06-6 18:00 2 years'  +%s` - `date +%s`)
#echo "-> 6.6.2012 + 2 roky: $(days $ZBYVA)"
#echo "\/--------------------------------------\/"
#echo "There is article about DSL http://www.paulgraham.com/index.html"

